/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface BulwarkXEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createEscrow"
      | "createEscrowToken"
      | "escrows"
      | "openDispute"
      | "refundEscrow"
      | "releaseEscrow"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EscrowCreated"
      | "EscrowDisputed"
      | "EscrowFunded"
      | "EscrowRefunded"
      | "EscrowReleased"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "createEscrow",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createEscrowToken",
    values: [AddressLike, AddressLike, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "escrows", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "openDispute",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "refundEscrow",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "releaseEscrow",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "createEscrow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createEscrowToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "escrows", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "openDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "refundEscrow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "releaseEscrow",
    data: BytesLike
  ): Result;
}

export namespace EscrowCreatedEvent {
  export type InputTuple = [
    escrowId: BytesLike,
    payer: AddressLike,
    payee: AddressLike,
    token: AddressLike,
    amount: BigNumberish,
    autoReleaseAt: BigNumberish
  ];
  export type OutputTuple = [
    escrowId: string,
    payer: string,
    payee: string,
    token: string,
    amount: bigint,
    autoReleaseAt: bigint
  ];
  export interface OutputObject {
    escrowId: string;
    payer: string;
    payee: string;
    token: string;
    amount: bigint;
    autoReleaseAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowDisputedEvent {
  export type InputTuple = [escrowId: BytesLike, caller: AddressLike];
  export type OutputTuple = [escrowId: string, caller: string];
  export interface OutputObject {
    escrowId: string;
    caller: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowFundedEvent {
  export type InputTuple = [escrowId: BytesLike];
  export type OutputTuple = [escrowId: string];
  export interface OutputObject {
    escrowId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowRefundedEvent {
  export type InputTuple = [escrowId: BytesLike, payer: AddressLike];
  export type OutputTuple = [escrowId: string, payer: string];
  export interface OutputObject {
    escrowId: string;
    payer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowReleasedEvent {
  export type InputTuple = [escrowId: BytesLike, payee: AddressLike];
  export type OutputTuple = [escrowId: string, payee: string];
  export interface OutputObject {
    escrowId: string;
    payee: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BulwarkXEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): BulwarkXEscrow;
  waitForDeployment(): Promise<this>;

  interface: BulwarkXEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createEscrow: TypedContractMethod<
    [
      _payee: AddressLike,
      _arbiter: AddressLike,
      _autoReleaseSeconds: BigNumberish
    ],
    [string],
    "payable"
  >;

  createEscrowToken: TypedContractMethod<
    [
      _payee: AddressLike,
      _arbiter: AddressLike,
      _token: AddressLike,
      _amount: BigNumberish,
      _autoReleaseSeconds: BigNumberish
    ],
    [string],
    "nonpayable"
  >;

  escrows: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, string, bigint, bigint, bigint, bigint] & {
        payer: string;
        payee: string;
        arbiter: string;
        token: string;
        amount: bigint;
        createdAt: bigint;
        autoReleaseAt: bigint;
        status: bigint;
      }
    ],
    "view"
  >;

  openDispute: TypedContractMethod<[escrowId: BytesLike], [void], "nonpayable">;

  refundEscrow: TypedContractMethod<
    [escrowId: BytesLike],
    [void],
    "nonpayable"
  >;

  releaseEscrow: TypedContractMethod<
    [escrowId: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createEscrow"
  ): TypedContractMethod<
    [
      _payee: AddressLike,
      _arbiter: AddressLike,
      _autoReleaseSeconds: BigNumberish
    ],
    [string],
    "payable"
  >;
  getFunction(
    nameOrSignature: "createEscrowToken"
  ): TypedContractMethod<
    [
      _payee: AddressLike,
      _arbiter: AddressLike,
      _token: AddressLike,
      _amount: BigNumberish,
      _autoReleaseSeconds: BigNumberish
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "escrows"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, string, bigint, bigint, bigint, bigint] & {
        payer: string;
        payee: string;
        arbiter: string;
        token: string;
        amount: bigint;
        createdAt: bigint;
        autoReleaseAt: bigint;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "openDispute"
  ): TypedContractMethod<[escrowId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "refundEscrow"
  ): TypedContractMethod<[escrowId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "releaseEscrow"
  ): TypedContractMethod<[escrowId: BytesLike], [void], "nonpayable">;

  getEvent(
    key: "EscrowCreated"
  ): TypedContractEvent<
    EscrowCreatedEvent.InputTuple,
    EscrowCreatedEvent.OutputTuple,
    EscrowCreatedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowDisputed"
  ): TypedContractEvent<
    EscrowDisputedEvent.InputTuple,
    EscrowDisputedEvent.OutputTuple,
    EscrowDisputedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowFunded"
  ): TypedContractEvent<
    EscrowFundedEvent.InputTuple,
    EscrowFundedEvent.OutputTuple,
    EscrowFundedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowRefunded"
  ): TypedContractEvent<
    EscrowRefundedEvent.InputTuple,
    EscrowRefundedEvent.OutputTuple,
    EscrowRefundedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowReleased"
  ): TypedContractEvent<
    EscrowReleasedEvent.InputTuple,
    EscrowReleasedEvent.OutputTuple,
    EscrowReleasedEvent.OutputObject
  >;

  filters: {
    "EscrowCreated(bytes32,address,address,address,uint256,uint64)": TypedContractEvent<
      EscrowCreatedEvent.InputTuple,
      EscrowCreatedEvent.OutputTuple,
      EscrowCreatedEvent.OutputObject
    >;
    EscrowCreated: TypedContractEvent<
      EscrowCreatedEvent.InputTuple,
      EscrowCreatedEvent.OutputTuple,
      EscrowCreatedEvent.OutputObject
    >;

    "EscrowDisputed(bytes32,address)": TypedContractEvent<
      EscrowDisputedEvent.InputTuple,
      EscrowDisputedEvent.OutputTuple,
      EscrowDisputedEvent.OutputObject
    >;
    EscrowDisputed: TypedContractEvent<
      EscrowDisputedEvent.InputTuple,
      EscrowDisputedEvent.OutputTuple,
      EscrowDisputedEvent.OutputObject
    >;

    "EscrowFunded(bytes32)": TypedContractEvent<
      EscrowFundedEvent.InputTuple,
      EscrowFundedEvent.OutputTuple,
      EscrowFundedEvent.OutputObject
    >;
    EscrowFunded: TypedContractEvent<
      EscrowFundedEvent.InputTuple,
      EscrowFundedEvent.OutputTuple,
      EscrowFundedEvent.OutputObject
    >;

    "EscrowRefunded(bytes32,address)": TypedContractEvent<
      EscrowRefundedEvent.InputTuple,
      EscrowRefundedEvent.OutputTuple,
      EscrowRefundedEvent.OutputObject
    >;
    EscrowRefunded: TypedContractEvent<
      EscrowRefundedEvent.InputTuple,
      EscrowRefundedEvent.OutputTuple,
      EscrowRefundedEvent.OutputObject
    >;

    "EscrowReleased(bytes32,address)": TypedContractEvent<
      EscrowReleasedEvent.InputTuple,
      EscrowReleasedEvent.OutputTuple,
      EscrowReleasedEvent.OutputObject
    >;
    EscrowReleased: TypedContractEvent<
      EscrowReleasedEvent.InputTuple,
      EscrowReleasedEvent.OutputTuple,
      EscrowReleasedEvent.OutputObject
    >;
  };
}
