/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ReenterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "attemptedReenter"
      | "cachedEscrowId"
      | "escrow"
      | "receiveAndReenter"
      | "setEscrowId"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "attemptedReenter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cachedEscrowId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "escrow", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "receiveAndReenter",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setEscrowId",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "attemptedReenter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cachedEscrowId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "escrow", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "receiveAndReenter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setEscrowId",
    data: BytesLike
  ): Result;
}

export interface Reenter extends BaseContract {
  connect(runner?: ContractRunner | null): Reenter;
  waitForDeployment(): Promise<this>;

  interface: ReenterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  attemptedReenter: TypedContractMethod<[], [boolean], "view">;

  cachedEscrowId: TypedContractMethod<[], [string], "view">;

  escrow: TypedContractMethod<[], [string], "view">;

  receiveAndReenter: TypedContractMethod<
    [escrowId: BytesLike],
    [void],
    "nonpayable"
  >;

  setEscrowId: TypedContractMethod<[escrowId: BytesLike], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "attemptedReenter"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "cachedEscrowId"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "escrow"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "receiveAndReenter"
  ): TypedContractMethod<[escrowId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setEscrowId"
  ): TypedContractMethod<[escrowId: BytesLike], [void], "nonpayable">;

  filters: {};
}
